[package]
name = "blob"
type = "lib"
authors = [""]
compiler_version = ">=0.30.0"

[dependencies]
bigint = {tag = "tf/update-to-le-bytes", git = "https://github.com/noir-lang/noir-bignum" }
types = { path = "../types" }
