# Reusable setup workflow for CI tasks
name: Setup Workflow
description: "Reusable setup steps"

inputs:
  runner_type:
    required: true
  spot_strategy:
    default: BestEffort
  images_to_pull:
    required: true
  username:
    required: false
  run:
    required: true
  ttl:
    required: false
    description: "Time to live for the tester instance in minutes"
    default: 45
runs:
  # define an action, runs in OS of caller
  using: composite
  steps:
    - name: Pull Docker Images
      uses: ./.github/ensure-tester
      with:
        username: ${{ inputs.username }}
        runner_type: ${{ inputs.runner_type}}
        spot_strategy: ${{ inputs.spot_strategy }}
        ttl: ${{ inputs.ttl }}
        run: |
          set -eux
          for image in ${{ inputs.images_to_pull }}; do
            docker pull $image
          done

    - name: Test
      uses: ./.github/run-on-tester
      if: ${{ env.CACHE_SUCCESS != 'true' }}
      with:
        run: ${{ inputs.run }}
