aztec:
  slotDuration: 24
  epochDuration: 4
  proofSubmissionWindow: 8
  realProofs: true


ethereum:
  blockTime: 12
  execution:
    resources:
      requests:
        memory: "2Gi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "200m"
  beacon:
    resources:
      requests:
        memory: "2Gi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "200m"
  validator:
    resources:
      requests:
        memory: "2Gi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "200m"

validator:
  replicas: 1
  validator:
    disabled: false

proverAgent:
  replicas: 6
  bb:
    hardwareConcurrency: 16
  resources:
    requests:
      memory: "64Gi"
      cpu: "16"
    limits:
      memory: "96Gi"
      cpu: "16"

bot:
  enabled: true
  txIntervalSeconds: 200

jobs:
  deployL1Verifier:
    enable: true
