global:
    cache_size_pct: 50
    disable_analytics: true
    disable_log_sharing: true
    buildkit_max_parallelism: 100
    container_frontend: docker-shell
buildkit_additional_args: ["-e", "BUILDKIT_STEP_LOG_MAX_SIZE=-1"]
