name: otel
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    configs:
      - source: otel-collector-config
        target: /etc/otelcol-contrib/config.yaml
    profiles:
      - metrics
    ports:
      - 4317:4317
      - 4318:4318

  prometheus:
    image: prom/prometheus
    profiles:
      - metrics
    ports:
      - 2112:2112
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    profiles:
      - metrics
    volumes:
      - ./helm-charts/aztec-network/files/grafana_dashboards:/etc/grafana/provisioning/dashboards
      - grafana:/var/lib/grafana
    configs:
      - source: grafana-sources
        target: /etc/grafana/provisioning/datasources/default.yml

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
    profiles:
      - metrics

configs:
  grafana-sources:
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          uid: aztec-node-metrics
          type: prometheus
          url: http://prometheus:9090
          editable: false
          isDefault: true
          jsonData:
            timeInterval: 10s

  prometheus-config:
    content: |
      global:
        evaluation_interval: 15s
        scrape_interval: 15s
      scrape_configs:
        - job_name: otel-collector
          static_configs:
          - targets: ['otel-collector:8888']
        - job_name: aztec
          static_configs:
          - targets: ['otel-collector:8889']
  otel-collector-config:
    content: |
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318

      processors:
        batch:

      exporters:
        prometheus:
          endpoint: 0.0.0.0:8889
          metric_expiration: 5m
        otlp/jaeger:
            endpoint: "jaeger:4317"
            tls:
              insecure: true

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/jaeger]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus]