name: Run on Builder
description: "Target builder with actions"

inputs:
  run:
    required: true
runs:
  # define an action, runs in OS of caller
  using: composite
  steps:
    # Assumes ensure-tester has ran
    - name: Run On Tester
      env:
        GITHUB_TOKEN: ${{ github.token }}
        # avoid double shell interpolation
        RUN_SCRIPT: |
          set -eux ;
          export GITHUB_REF_NAME=${{ github.ref_name }} ;
          cd ~/run-${{ github.run_id }} ;
          ${{ inputs.run }}
      shell: bash
      run: scripts/run_on_tester "$RUN_SCRIPT"
