{{- if not .Values.ethereum.externalHost }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aztec-network.fullname" . }}-eth-beacon
  labels:
    {{- include "aztec-network.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aztec-network.selectorLabels" . | nindent 6 }}
      app: eth-beacon
  template:
    metadata:
      labels:
        {{- include "aztec-network.selectorLabels" . | nindent 8 }}
        app: eth-beacon
    spec:
      {{- if .Values.network.public }}
      hostNetwork: true
      {{- end }}
      containers:
        - name: eth-beacon
          image: "{{ .Values.images.lighthouse.image }}"
          imagePullPolicy: {{ .Values.images.lighthouse.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            # Genesis information is copied such that we can write into it
            # First serialize the ssz file
            - >-
              cp -r /genesis-template /genesis &&
              base64 -d /genesis/genesis-ssz > /genesis/genesis.ssz &&

              cat /genesis/jwt-secret.hex &&

              lighthouse bn
              --disable-peer-scoring
              --disable-packet-filter
              --enable-private-discovery
              --disable-enr-auto-update
              --staking
              --http
              --http-address=0.0.0.0
              --http-port=5052
              --validator-monitor-auto
              --http-allow-origin='*'
              --listen-address=0.0.0.0
              {{- include "helpers.flag" (list "port" .Values.ethereum.beacon.port) }}
              --target-peers=0
              --testnet-dir=/genesis
              --execution-endpoints="http://{{ include "aztec-network.fullname" . }}-eth-execution.{{ .Release.Namespace }}.svc.cluster.local:8551"
              --execution-jwt-secret-key="61e1dd9539e8cc37b3d71dcf8ce372f0e119cc1c73426ee80472a4214f2a41a1"
              --allow-insecure-genesis-sync
              --debug-level=debug
          volumeMounts:
            - name: shared-volume
              mountPath: /data
            - name: genesis
              mountPath: /genesis-template
          resources:
            # NOTE: new path here
            {{- toYaml .Values.ethereum.beacon.resources | nindent 12 }}
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ include "aztec-network.fullname" . }}-eth-beacon-pvc
        - name: genesis
          configMap:
            name: {{ include "aztec-network.fullname" . }}-eth-beacon-genesis
{{if not .Values.network.public }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aztec-network.fullname" . }}-eth-beacon
  labels:
    {{- include "aztec-network.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ethereum.beacon.service.type }}
  selector:
    {{- include "aztec-network.selectorLabels" . | nindent 4 }}
    app: eth-beacon
  ports:
    - protocol: TCP
      port: {{ .Values.ethereum.beacon.service.port }}
      targetPort: {{ .Values.ethereum.beacon.service.targetPort }}
      {{- if and (eq .Values.ethereum.beacon.service.type "NodePort") .Values.ethereum.beacon.service.nodePort }}
      nodePort: {{ .Values.ethereum.beacon.service.nodePort }}
      {{- end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aztec-network.fullname" . }}-eth-beacon-genesis
  labels:
    {{- include "aztec-network.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Files.Get "eth-devnet/out/config.yaml" | nindent 4 }}
  deposit_contract_block.txt: |
    {{ .Files.Get "eth-devnet/out/deposit_contract_block.txt" | nindent 4 }}
  jwt-secret.hex: |
    {{ .Files.Get "eth-devnet/out/jwt-secret.hex" | nindent 4 }}
  genesis-ssz: |
    {{ .Files.Get "eth-devnet/out/genesis-ssz" | nindent 4 }}
---
{{- if gt (.Values.ethereum.replicas | int) 0 }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aztec-network.fullname" . }}-eth-beacon-pvc
  labels:
    {{- include "aztec-network.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.ethereum.beacon.storage }}
{{- end }}
---
{{ end }}
