# Default values for additional validators
nameOverride: ""
fullnameOverride: ""

# These values will be populated from the main Aztec network deployment
network:
  p2pBootstrapNodesAsFullPeers: true
  l1ExecutionUrl: ""
  l1ConsensusUrl: ""

storage:
  localSsd: false
  dataStoreMapSize: "134217728" # 128 GB
  worldStateMapSize: "134217728" # 128 GB

telemetry:
  enabled: false
  useGcloudLogging: true
  excludeMetrics: ""

images:
  aztec:
    image: aztecprotocol/aztec
    pullPolicy: IfNotPresent
  curl:
    image: curlimages/curl:7.81.0
    pullPolicy: IfNotPresent

aztec:
  slotDuration: 36
  epochDuration: 32
  proofSubmissionWindow: 64
  testAccounts: true
  realProofs: false

ethereum:
  chainId: 31337
  blockTime: 12

validator:
  # This will be set by the install script
  bootNodes: "enr:-La4QAXITCh6x60GnySW1Tv8xbGO7ZvdCpSzq5BDBRGX44yXBGGvv62QS-A_hyH-2t-kBfqZuVvFcbkUiw1LeHvh3BcGhWF6dGVjpDAwLTEzMzctZjQ4YWNlYjQtMS0wNTNiZDlkOS0yNmU5N2I2MYJpZIJ2NIJpcIQK9ABhiXNlY3AyNTZrMaECx8cwlwBKDMyy-Fd9A3fqP_EAOnXTysWoJAl8AjWuOYiDdGNwgp3Qg3VkcIKd0A"
  privateKeys: ["0x3fde152c3df55eff94d3ac60b601f08b830e6bf97a0a2b6d2e3daa36b1dc3dc8"]
  replicas: 1
  service:
    p2pPort: 40400
    nodePort: 8080
  logLevel: "debug; info: aztec:simulator, json-rpc"
  sequencer:
    maxSecondsBetweenBlocks: 0
    minTxsPerBlock: 0
    maxTxsPerBlock: 4
    enforceTimeTable: true
  validator:
    disabled: false
    reexecute: true
  p2p:
    enabled: "true"
    floodPublish: true
  startupProbe:
    periodSeconds: 10
    # Only if we fail for 20 minutes straight do we call it botched
    # This gives enough time to sync
    failureThreshold: 120
  maxOldSpaceSize: "4608"
  attestationPollingInterval: 1000
  l1GasLimitBufferPercentage: 20
  l1GasPriceMax: 100000000000
  dataDir: "/data"
  storageSize: "1Gi"

