apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  annotations:
    name: alpha-nodes-backend-config
    namespace: alpha-nodes
spec:
  healthCheck:
    checkIntervalSec: 15
    healthyThreshold: 2
    port: 8080
    requestPath: /status
    timeoutSec: 5
    type: HTTP
    unhealthyThreshold: 2
