name: Run on Builder
description: "Target builder with actions"

inputs:
  run:
    required: true
runs:
  # define an action, runs in OS of caller
  using: composite
  steps:
    # Assumes ensure-builder has ran and BUILDER_SPOT_IP/BUILDER_SPOT_KEY are defined
    - name: Run On Builder
      env:
        GITHUB_TOKEN: ${{ github.token }}
        # avoid double shell interpolation
        RUN_SCRIPT: |
          set -eux ;
          sudo shutdown -P 40 ;
          export GITHUB_REF_NAME=${{ github.ref_name }} ;
          cd ~/run-${{ github.run_id }} ;
          ${{ inputs.run }}
      shell: bash
      run: scripts/run_on_builder "$RUN_SCRIPT"
